<a href="https://colab.research.google.com/github/IsaacKelly99/IKR/blob/master/wikipedia_recomendations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Wikipedia recommender 
## ML unsupervised learning

I created a wikipedia recommender program using NMF from the sckit learn-  decomposition module

Other tools used:
- TfidfVectorizer, to create a tfidf from the dataframe
- normalize
- TruncatedSVD
- make_pipeline
- Kmeans, for clustering
- pandas: read_csv, loc, dot, etc.
- numpy

The wikipedia dataset: https://www.lateral.io/resources-blog/the-unknown-perils-of-mining-wikipedia

This excercise was part of the 'Unsupervised learning in python' course from datacamp

In [13]:
import pandas as pd
import numpy as np

In [14]:
wiki = pd.read_csv("/content/drive/MyDrive/data_for_colab/wikipedia-vectors.csv")

In [15]:
wiki.head()

Unnamed: 0  HTTP 404  ...   Sepsis  Adam Levine
0           0       0.0  ...  0.00000          0.0
1           1       0.0  ...  0.00611          0.0
2           2       0.0  ...  0.00000          0.0
3           3       0.0  ...  0.00000          0.0
4           4       0.0  ...  0.00000          0.0

[5 rows x 61 columns]

In [16]:
# Import TfidfVectorizer from sklearn extraction tet
from sklearn.feature_extraction.text import TfidfVectorizer
# Create a TfidfVectorizer
tfidf = TfidfVectorizer()
# Apply fit_transform to document to turn wiki into a tfidf, the new variable is csr_mat
csr_mat = tfidf.fit_transform(wiki)
# Print result of toarray() method
print(csr_mat.toarray())
# Get the words, stored as feature names in the tfidf
words = tfidf.get_feature_names()
# get the name of the columns as a np array
titles = np.array(wiki.columns)
articles = csr_mat
# Print words
print(words)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['2007', '2010', '2014', '350', '404', 'action', 'adam', 'alexa', 'angelina', 'aniston', 'anne', 'appropriate', 'arctic', 'arsenal', 'biel', 'black', 'by', 'catherine', 'chad', 'change', 'chili', 'climate', 'colombia', 'conference', 'connie', 'cookie', 'cristiano', 'crowe', 'cup', 'dakota', 'denzel', 'doxycycline', 'emissions', 'explorer', 'falcao', 'fanning', 'fassbender', 'fever', 'fifa', 'firefox', 'football', 'france', 'franck', 'gabapentin', 'gas', 'global', 'google', 'gout', 'greenhouse', 'hathaway', 'hedegaard', 'hepatitis', 'hot', 'http', 'hypertext', 'ibrahimović', 'internet', 'jennifer', 'jessica', 'jolie', 'jones', 'kroeger', 'kunis', 'kyoto', 'lawson', 'leukemia', 'levine', 'linkedin', 'lymphoma', 'michael', 'mila', 'mitigation', 'monkeys', 'nate', 'national', 'nationally', 'nations', 'neymar', 'nicks', 'nigel', 'org', '

In [17]:
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import make_pipeline
from sklearn.cluster import KMeans
# Create a TruncatedSVD instance called svd
svd = TruncatedSVD(n_components=50)
# Create a KMeans instance called kmeans, with 6 clusters
kmeans = KMeans(n_clusters=6)
# Create a pipeline named pipeline
pipeline = make_pipeline(svd, kmeans)
# fit it to tdif articles
pipeline.fit(articles)
# Calculate/predict the cluster labels as labels
labels = pipeline.predict(articles)
# Create a DataFrame aligning labels and titles as df
df = pd.DataFrame({'label': labels, 'article': titles})
# Display df sorted by cluster label, using sort_values
print(df.sort_values("label"))

    label                                        article
59      0                                         Sepsis
49      1                                     Gabapentin
0       2                                     Unnamed: 0
32      2                              Cristiano Ronaldo
33      2                                   Arsenal F.C.
..    ...                                            ...
15      4                                 Climate change
20      4  2007 United Nations Climate Change Conference
36      5                Colombia national football team
31      5                  France national football team
38      5                                       Football

[61 rows x 2 columns]


We can see that some football teams have similar labels, sucho as the colombian, and french national team (5), the arsenal and Cristiano ronaldo have the same labels as well (2), and the climate related articles such as the ONU conference and the Climate change article are labeled as 4

In [18]:
# Import NMF
from sklearn.decomposition import NMF
#number of components for the Nmf 
fnmf= 6 
# Create an NMF instance with 6 components, assigned to model
model = NMF(n_components= fnmf)
# Fit the model to articles
model.fit(articles)
# Transform the articles
nmf_features = model.transform(articles)
# Print the NMF features
print(nmf_features.round(2))


[[0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.8 ]
 [0.   0.   0.   0.59 0.   0.  ]
 [0.   0.   0.   0.59 0.   0.  ]
 [0.   0.   0.   0.   0.   0.8 ]
 [0.   0.   0.   0.   0.68 0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.68 0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.63 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.15 0.   0.   0.   0.   0.  ]
 [0.74 0.   0.   0.   0.   0.  ]
 [0.74 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0. 

In [19]:
# Import pandas
import pandas as pd
# Create a pandas DataFrame: df
df = pd.DataFrame(nmf_features, index=titles)
# Print the row for 'Google Search'
print(df.loc["Google Search"])

0    0.000000
1    0.000000
2    0.000000
3    0.000000
4    0.682035
5    0.000000
Name: Google Search, dtype: float64


In [20]:
# Create a DataFrame,called components_df, using the words as columns
components_df = pd.DataFrame(model.components_,columns=words)
# Print the shape of the DataFrame
print(components_df.shape)
# Select row 3: component
component = components_df.iloc[3]
# Print result of nlargest
print(component.nlargest())

(6, 111)
internet       1.138759e+00
alexa          6.266867e-01
explorer       6.266867e-01
fever          3.294263e-10
tonsillitis    2.719892e-10
Name: 3, dtype: float64


In [21]:
# import normalize to use on the data
from sklearn.preprocessing import normalize
# Normalizing the NMF features
norm_features = normalize(nmf_features)
# Create a DataFrame with the normalized features
df = pd.DataFrame(norm_features, index=titles)

In [22]:
# a look on the dataframe, this is how our normalized articles look like
df.head(3)

0             1    2    3    4    5
Unnamed: 0      0.0  1.228529e-09  0.0  0.0  1.0  0.0
HTTP 404        0.0  0.000000e+00  0.0  0.0  0.0  1.0
Alexa Internet  0.0  0.000000e+00  0.0  1.0  0.0  0.0

In [24]:
# Select the row corresponding to 'X': article
article = df.loc['Google Search']
# Compute the dot products, using df.dot, and assing them to similarities
similarities = df.dot(article)
# Display the dit products with the largest cosine similarity
print(similarities.nlargest())
# We can see that the largest values are related articles

Unnamed: 0                     1.0
Google Search                  1.0
Tumblr                         1.0
Hypertext Transfer Protocol    1.0
Social search                  1.0
dtype: float64


We can see that the related articles are assigned largest values, this is how a basic search engine works, based on our prefferences it recomends videos, articles, or posts based on its similarity to the ones we've previously seen or liked.